export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_LIKE_REQUEST = "MOVIE_LIKE_REQUEST";
export const MOVIE_LIKE_SUCCESS = "MOVIE_LIKE_SUCCESS";
export const MOVIE_LIKE_FAIL = "MOVIE_LIKE_FAIL";

export const INIT_STATE_MOVIE = " INIT_STATE_MOVIE";
